### ISSUE TITLE
Terrain quickstart guide failing on MacOS with "cannot get submodules without a working tree" error

### ISSUE THREAD

**Issue by dan-turner** [terra-money/terrain#16]
Hi folks,

I've been trying all afternoon to get the Terrain quickstart up and going on my Intel MacBook Pro.  I've been following the instructions here:

https://docs.terra.money/docs/develop/dapp/quick-start/README.html

In summary:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

rustup default stable
rustup target add wasm32-unknown-unknown
cargo install cargo-generate --features vendored-openssl
cargo install cargo-run-script

nvm use 16     # see: https://github.com/nvm-sh/nvm

npm install -g @terra-money/terrain
```

All of the above works, but when I attempt to generate the scaffold, this happens:

```
› terrain new my-terra-dapp
generating:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 17, message: "cannot get submodules without a working tree" }', /Users/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-generate-0.13.0/src/git/utils.rs:203:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
- contract... !
    Error: Command failed: cargo generate --git https://github.com/CosmWasm/cw-template.git --branch 0.16 --name
    counter
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 17, message:
    "cannot get submodules without a working tree" }',
    /Users/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-generate-0.13.0/src/git/utils.rs:203:38
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Initially I thought perhaps Terrain might have straight up been broken, so I attempted to repro with a Dockerfile, only to discover that it worked.

Any ideas what might be wrong?

Cheers,
Dan.

MacOS version: `12.3.1 (21E258)`

**Comment by dan-turner** [comment]
```
› RUST_BACKTRACE=full cargo generate --git https://github.com/CosmWasm/cw-template.git --branch 0.16 --name counter
⚠️   Unable to load config file: /Users/dan/.cargo/cargo-generate.toml
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 17, message: "cannot get submodules without a working tree" }', /Users/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-generate-0.13.0/src/git/utils.rs:203:38
stack backtrace:
   0:        0x1041fb60f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4f26ffad025fdbe8
   1:        0x103ee94ab - core::fmt::write::h0a9937d83d3944c1
   2:        0x1041f9d9a - std::io::Write::write_fmt::hfaf2e2e92eda8127
   3:        0x1041ff4ee - std::panicking::rust_panic_with_hook::hef4f5e524db188b3
   4:        0x1041fee3a - std::panicking::begin_panic_handler::{{closure}}::h6e8805ea2351af89
   5:        0x1041fedb9 - std::sys_common::backtrace::__rust_end_short_backtrace::hd383ade987b76f63
   6:        0x1041fed75 - _rust_begin_unwind
   7:        0x10433028f - core::panicking::panic_fmt::hb58956db718d5b79
   8:        0x104330525 - core::result::unwrap_failed::he6d7833eae74c72a
   9:        0x103e5c481 - cargo_generate::git::utils::create::h7973b563fdb58dba
  10:        0x103e1ea8f - cargo_generate::generate::h0fcd75ac42d6cd8d
  11:        0x103e9b8a0 - cargo_generate::main::h2a47d262d395f1e6
  12:        0x103e990f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::he0f6f6be64c42b16
  13:        0x103e995dd - _main
```

**Comment by octalmage** [comment]
Hey @dan-turner, we're currently in the process of removing cargo-generate as a dependency, it ends up causing a lot of issues. should have a solution for this soon!

**Comment by dan-turner** [comment]
No probs y'all! Thanks for the quick reply :)

If anyone else encounters this in the meantime, I was able to unblock myself by using the attached Dockerfile and the below:

```
docker build -t terrain .
docker run -it -v /<some absolute path on host>:/home/rusty/dapp terrain

cd dapp
terrain new my-terra-dapp
```

[Dockerfile.txt](https://github.com/terra-money/terrain/files/8447562/Dockerfile.txt)

**Comment by octalmage** [comment]
This should be fully resolved, we no longer rely on cargo generate. Please reopen if anyone is still seeing this error.
